name: Ruby

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 3.4

  build:
    needs: ruby-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        parser: [parse.y, prism]
        include:
          - { ruby: 3.2, parser: 'parse.y' }
          - { ruby: 3.3, parser: 'parse.y' }
    steps:
    - uses: actions/checkout@v7
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    # Ruby 3.2 does not have a --parser option
    - name: Run the test suite (3.2+)
      run: |
        RUBYOPT="--disable-error_highlight --parser=${{ matrix.parser }}" bundle exec rake TESTOPT=-v
      if: ${{ matrix.ruby != '3.2' }}
    - name: Run the test suite (3.2)
      run: |
        RUBYOPT="--disable-error_highlight" bundle exec rake TESTOPT=-v
      if: ${{ matrix.ruby == '3.2' }}
